"""Rebuild annotated/ and notes/QUESTIONS.md from the source text + cards.

Always a full rebuild from the untouched source, never an incremental edit of
a previous build -- that is what makes repeated runs idempotent. Nothing in
annotated/ is a source of truth; edit notes/cards/ instead.

Usage:
    python build_annotated.py <paper_root> [--allow-drift]
"""

from __future__ import annotations

import posixpath
import re
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import miniyaml
import paperkit

paperkit.bootstrap()

STATUS_LABEL = {"open": "未解決", "half": "半懂", "resolved": "已解決"}
STATUS_ICON = {"open": "🔴", "half": "🟡", "resolved": "🟢"}

GENERATED_BANNER = (
    "<!-- GENERATED by paper-annotations — 請勿手改。\n"
    "     權威原文：{source}\n"
    "     疑問卡來源：notes/cards/\n"
    "     重新產生：python <scripts>/build_annotated.py <本次的路徑> -->\n"
)

ANNOTATED_AGENTS = """# Annotated View — Reading Policy

本目錄是**衍生檔**，由 `notes/cards/` 與原文合併產生。

1. 權威原文在 `../sections/`（或該論文套件的原始 Markdown），**引用論文內容一律以原文為準**。
2. 本目錄檔案中 `<details>` 區塊內的文字是**使用者的提問與 AI 的解說**，屬於閱讀筆記，
   **不是論文內容，不得作為論文原文引用或轉述為作者主張**。
3. 不要編輯本目錄任何檔案；修改請改 `../notes/cards/*.md` 後重新執行 build。
4. 疑問索引在 `../notes/QUESTIONS.md`。

本檔案為新增，不覆寫論文套件原有的 `AGENTS.md` 閱讀政策。
"""





def summary_text(card) -> str:
    """The whole question, on one line.

    Never shortened: the collapsed card is what the reader faces during review,
    and a half-shown question cannot be answered from memory. Long questions
    make a taller summary -- that is the right trade here.
    """
    sections = paperkit.card_sections(card["body"])
    question = sections.get("問題") or sections.get("Question") or ""
    return " ".join(question.split()) or "(未填問題)"


def render_card(card, dst_path: Path) -> str:
    meta, sections = card["meta"], paperkit.card_sections(card["body"])
    cid = str(meta.get("id", "?"))
    status = str(meta.get("status", "open"))
    icon = STATUS_ICON.get(status, "⚪")
    label = STATUS_LABEL.get(status, status)
    title = summary_text(card)

    origin = str(meta.get("origin", "asked"))
    tag_list = " ".join(str(t) for t in (meta.get("tags") or []))
    parts = [
        f"<!-- card:{cid} -->",
        # data-* attributes are inert in Markdown and let the HTML view filter;
        # the id gives the question list something to jump to.
        f'<details class="qcard" id="card-{cid}" data-id="{cid}" data-status="{status}" '
        f'data-origin="{origin}" data-tags="{tag_list}">',
        f"<summary>{icon} <b>Q{cid}</b> · {title} <sub>[{label}]</sub></summary>",
        "",
    ]

    # The question is not repeated in the body -- the summary already carries it
    # in full, whether the card is collapsed or open.
    for key, prefix in (("卡點", "**卡點**："), ("解答", "**解答**\n\n"), ("一句話直覺", "**一句話直覺**：")):
        value = (sections.get(key) or "").strip()
        if value:
            parts += [prefix + value, ""]

    meta_bits = [f"狀態 {label}"]
    if meta.get("origin") == "suggested":
        meta_bits.append("AI 提示（非你提問）")
    if meta.get("created"):
        meta_bits.append(f"建立 {meta['created']}")
    tags = meta.get("tags") or []
    if tags:
        meta_bits.append("標籤 " + ", ".join(str(t) for t in tags))
    link = paperkit.rel_href(dst_path, card["path"])
    meta_bits.append(f'<a href="{link}">卡片原始檔</a>')
    parts += ["<sub>" + " · ".join(meta_bits) + "</sub>", "", "</details>", ""]
    return "\n".join(parts)


def check_drift(paper_root: Path, config: dict):
    recorded = config.get("fingerprint", {}).get("files") or {}
    stale, missing = [], []
    for rel, digest in recorded.items():
        path = paper_root / rel
        if not path.is_file():
            missing.append(rel)
        elif paperkit.file_fingerprint(path) != digest:
            stale.append(rel)
    # A file added since the probe would otherwise be skipped in silence:
    # never annotated, never mentioned.
    current = {rel.as_posix() for rel in paperkit.discover_sources(paper_root)}
    added = sorted(current - set(recorded))
    return stale, missing, added


def build(work_root: Path, allow_drift: bool = False):
    config, paper_root, notes, annotated_root = paperkit.load_workspace(work_root)

    stale, missing, added = check_drift(paper_root, config)
    if (stale or missing or added) and not allow_drift:
        print("⚠️  論文原文和上次檢查時不一樣了，已停止建置：")
        for rel in missing:
            print(f"    檔案不見了   {rel}")
        for rel in stale:
            print(f"    內容有變動   {rel}")
        for rel in added:
            print(f"    多了新檔案   {rel}")
        if stale or missing:
            print("\n原文可能被重新轉檔或重新切分，你的筆記有掛錯位置的風險。請先執行：")
            print("    python <scripts>/reanchor.py <本次的路徑>")
            print("確認每則筆記都還掛在該在的地方，再重新建置。")
        else:
            print("\n新檔案不會被納入筆記，除非重新探測一次：")
            print("    python <scripts>/probe.py <論文路徑> [--out <筆記路徑>]")
        print("若確定這次變動跟筆記位置無關，可加 --allow-drift 略過這項檢查。")
        return 2

    card_problems = []
    cards = paperkit.load_cards(notes, card_problems)
    by_file = {}
    for card in cards:
        anchor = card["meta"].get("anchor") or {}
        by_file.setdefault(str(anchor.get("file") or ""), []).append(card)

    sources = [Path(p) for p in (config.get("sources") or [])]
    placed, unanchored, rows, fragile = {}, [], [], []

    for order, rel in enumerate(sources):
        src = paper_root / rel
        if not src.is_file():
            continue
        lines = src.read_text(encoding="utf-8").splitlines()
        dst = annotated_root / rel

        insertions = []
        for card in by_file.get(rel.as_posix(), []):
            index, method = paperkit.resolve_anchor(card["meta"].get("anchor") or {}, lines)
            if index is None:
                unanchored.append((card, method))
                continue
            insertions.append((index, method, card))
            placed[str(card["meta"].get("id"))] = True
            # Check the quote even when the card anchored via ref/heading: a bad
            # quote stays invisible until the day the paper is re-converted,
            # which is exactly the day it is needed.
            anchor = card["meta"].get("anchor") or {}
            hits = paperkit.count_quote(lines, paperkit.quote_text(anchor.get("quote")))
            if hits != 1:
                fragile.append((card, hits))

        out = list(lines)
        for index, method, card in sorted(insertions, key=lambda x: -x[0]):
            block = render_card(card, dst).splitlines()
            out[index + 1 : index + 1] = [""] + block

        for index, method, card in insertions:
            rows.append(
                {
                    "order": (order, index),
                    "card": card,
                    "method": method,
                    "file_rel": rel,
                    "dst": dst,
                }
            )

        text = "\n".join(out).rstrip("\n") + "\n"
        text = paperkit.rewrite_links(text, src.parent, dst.parent)
        banner = GENERATED_BANNER.format(source=rel.as_posix())
        # keep the banner below any YAML frontmatter, or it stops being frontmatter
        match = paperkit.FRONTMATTER_RE.match(text)
        if match:
            text = text[: match.end()] + "\n" + banner + text[match.end() :]
        else:
            text = banner + "\n" + text
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(text, encoding="utf-8", newline="\n")

    # drop files from a previous build that no longer correspond to a source
    keep = {(annotated_root / rel).resolve() for rel in sources}
    keep.add((annotated_root / "AGENTS.md").resolve())
    if annotated_root.is_dir():
        for path in annotated_root.rglob("*.md"):
            if path.resolve() not in keep:
                path.unlink()

    (annotated_root / "AGENTS.md").write_text(ANNOTATED_AGENTS, encoding="utf-8", newline="\n")

    for card in cards:
        cid = str(card["meta"].get("id"))
        if cid not in placed and not any(c["meta"].get("id") == card["meta"].get("id") for c, _ in unanchored):
            declared = (card["meta"].get("anchor") or {}).get("file") or "(未填)"
            unanchored.append((card, f"找不到這張卡指定的檔案：{declared}（原文可能被重新切分，執行 reanchor.py）"))

    write_index(paper_root, notes, config, rows, unanchored, cards, fragile, card_problems)

    print(f"annotated/  {len(sources)} 個檔案")
    print(f"疑問卡      {len(cards)} 張：已定位 {len(rows)}，找不到位置 {len(unanchored)}")
    for card, reason in unanchored:
        print(f"  ⚠️  Q{card['meta'].get('id')} — {reason} — {card['path'].name}")
    if card_problems:
        print("\n⚠️  這些卡片本身有問題：")
        for path, message in card_problems:
            print(f"    {path.name} — {message}")
    if fragile:
        print("\n🟡 引文提醒（這次照樣掛好了，但論文改版後會救不回來）：")
        for card, hits in fragile:
            print(f"    Q{card['meta'].get('id')} — {fragile_reason(hits)} — {card['path'].name}")
        print("    把 quote.exact 改成原文中獨一無二的一句話即可。")

    companions = drifted_companions(paper_root, config)
    if companions:
        print("\n🟡 這些檔案也變了（不影響筆記位置，僅供參考）：")
        for rel in companions:
            print(f"    {rel}")
    return 0


def fragile_reason(hits: int) -> str:
    if hits < 0:
        return "沒寫引文，或引文太短"
    if hits == 0:
        return "引文在這個檔案裡找不到"
    return f"引文在這個檔案裡出現 {hits} 次，不唯一"


def drifted_companions(paper_root: Path, config: dict):
    """document.md / INDEX.md / manifest.json changed but the sections did not.

    These cannot break an anchor -- notes hang on sections/ -- so this never
    stops a build. It is still worth saying: it usually means the package is
    internally inconsistent, or a re-conversion only half landed.
    """
    out = []
    for rel, digest in (config.get("fingerprint", {}).get("companions") or {}).items():
        path = paper_root / rel
        if not path.is_file():
            out.append(f"{rel}（檔案不見了）")
        elif paperkit.file_fingerprint(path) != digest:
            out.append(f"{rel}（內容有變動）")
    return out


def esc(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def anchor_display(card, method) -> str:
    anchor = card["meta"].get("anchor") or {}
    if anchor.get("ref"):
        kind, _, value = str(anchor["ref"]).partition(":")
        pretty = {"eq": "Eq.", "equation": "Eq.", "fig": "Fig.", "figure": "Fig.", "table": "Table "}
        if method.startswith("ref:"):
            return f"{pretty.get(kind.lower(), kind + ':')}{value}"
    return {"heading": "小節", "quote": "引文"}.get(method, method)


def write_index(paper_root: Path, notes: Path, config: dict, rows, unanchored, cards, fragile=(), card_problems=()):
    rows = sorted(rows, key=lambda r: r["order"])
    annotated_link = paperkit.rel_href(notes / "QUESTIONS.md", (notes.parent / "annotated" / "index.html"))
    lines = [
        "<!-- GENERATED by paper-annotations — 請勿手改，改 notes/cards/ 後重新 build。 -->",
        "",
        "# 疑問索引",
        "",
        f"論文套件：`{paper_root.name}` · Tier {config.get('tier', '?')} · "
        f"建置 {date.today().isoformat()} · built_by: python",
        "",
        f"共 {len(cards)} 張疑問卡（已定位 {len(rows)}，找不到位置 {len(unanchored)}）。",
        f"複習入口是 [`annotated/index.html`]({annotated_link})：原文中就地摺疊著你當初的問題，先自己想過再展開。",
        "",
    ]

    if card_problems:
        lines += [
            "## ⚠️ 卡片本身有問題",
            "",
            "這些檔案沒辦法正常當成疑問卡使用。**沒有 YAML 區塊的卡完全不會被讀取**，"
            "內容還在檔案裡，但不會出現在任何地方。",
            "",
            "| 卡片 | 問題 |",
            "|---|---|",
        ]
        for path, message in card_problems:
            lines.append(f"| [`{path.name}`](cards/{path.name}) | {esc(message)} |")
        lines.append("")

    if unanchored:
        lines += [
            "## ⚠️ 找不到位置的疑問",
            "",
            "這些疑問在原文中找不到對應位置，**不會出現在註記檢視裡**。請改卡片裡指定的那句原文，或執行 `reanchor.py`。",
            "",
            "| 卡片 | 原因 | 問題 |",
            "|---|---|---|",
        ]
        for card, reason in unanchored:
            lines.append(
                f"| [`{card['path'].name}`](cards/{card['path'].name}) | {esc(reason)} | {esc(summary_text(card))} |"
            )
        lines.append("")

    if fragile:
        lines += [
            "## 🟡 引文需要修補",
            "",
            "這些疑問目前掛得上，但它們指定的原文句子不唯一或找不到。"
            "論文一旦重新轉檔，就沒辦法自動找回位置——趁現在把 `quote.exact` 改成原文中獨一無二的一句。",
            "",
            "| 卡片 | 問題 | 狀況 |",
            "|---|---|---|",
        ]
        for card, hits in fragile:
            lines.append(
                f"| [`{card['path'].name}`](cards/{card['path'].name}) "
                f"| {esc(summary_text(card))} | {esc(fragile_reason(hits))} |"
            )
        lines.append("")

    pending = [r for r in rows if str(r["card"]["meta"].get("status", "open")) in ("open", "half")]
    if pending:
        lines += ["## 🔶 還沒完全懂", "", "| 狀態 | 問題 | 位置 |", "|---|---|---|"]
        for row in pending:
            card = row["card"]
            status = str(card["meta"].get("status", "open"))
            heading = (card["meta"].get("anchor") or {}).get("heading") or []
            where = esc(heading[-1]) if isinstance(heading, list) and heading else row["file_rel"].stem
            link = paperkit.rel_href(notes / "QUESTIONS.md", row["dst"])
            lines.append(
                f"| {STATUS_ICON.get(status, '⚪')} {STATUS_LABEL.get(status, status)} "
                f"| {esc(summary_text(card))} | [{where}]({link}) |"
            )
        lines.append("")

    lines += [
        "## 全部疑問（依論文順序）",
        "",
        "| # | 狀態 | 問題 | 小節 | 掛在哪 | 標籤 | 日期 | 卡片 |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        card = row["card"]
        meta = card["meta"]
        status = str(meta.get("status", "open"))
        anchor = meta.get("anchor") or {}
        heading = anchor.get("heading") or []
        where = esc(heading[-1]) if isinstance(heading, list) and heading else row["file_rel"].stem
        link = paperkit.rel_href(notes / "QUESTIONS.md", row["dst"])
        tags = ", ".join(str(t) for t in (meta.get("tags") or []))
        origin = " 💡" if meta.get("origin") == "suggested" else ""
        lines.append(
            f"| Q{meta.get('id')}{origin} | {STATUS_ICON.get(status, '⚪')} {STATUS_LABEL.get(status, status)} "
            f"| [{esc(summary_text(card))}]({link}) | {where} | {esc(anchor_display(card, row['method']))} "
            f"| {esc(tags)} | {esc(meta.get('created', ''))} | [卡片](cards/{card['path'].name}) |"
        )
    lines += ["", "💡 = 我主動標記的疑點，不是你問過的。", ""]

    (notes / "QUESTIONS.md").write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main(argv):
    args = [a for a in argv[1:] if not a.startswith("--")]
    return build(Path(args[0] if args else ".").resolve(), "--allow-drift" in argv)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
