"""Shared logic for paper-annotations: cards, sources, anchor resolution.

Design rule (see ADR 0001): anchors are RESOLVED, never DECLARED. Nothing here
trusts metadata about where a card belongs -- every anchor is matched against
the source text as it exists right now, and a card that cannot be matched is
reported as unanchored rather than silently placed.
"""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

import miniyaml


MIN_PYTHON = (3, 8)

GENERATED_MARK = "GENERATED by paper-annotations"

VALID_STATUS = ("open", "half", "resolved")
VALID_ORIGIN = ("asked", "suggested")


def bootstrap() -> None:
    """Guard the interpreter version and make the console printable.

    Windows consoles default to a legacy codepage that cannot print emoji;
    without the reconfigure, one warning symbol crashes the run with
    UnicodeEncodeError -- on exactly the code path that reports problems.
    """
    if sys.version_info < MIN_PYTHON:
        raise SystemExit(
            f"需要 Python {MIN_PYTHON[0]}.{MIN_PYTHON[1]} 以上，"
            f"目前是 {sys.version.split()[0]}"
        )
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            try:
                stream.reconfigure(encoding="utf-8", errors="replace")
            except (ValueError, OSError):
                pass

FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n?", re.DOTALL)

# Files that are never paper content, whatever tier we are in.
META_FILENAMES = {
    "readme.md",
    "index.md",
    "agents.md",
    "claude.md",
    "questions.md",
    "contributing.md",
    "changelog.md",
    "license.md",
}
META_DIRNAMES = {"notes", "annotated", "validation", "docs", ".git", "tools"}


# --------------------------------------------------------------------------
# frontmatter documents (cards)
# --------------------------------------------------------------------------


def read_doc(path: Path):
    """Return (meta, body) for a markdown file with YAML frontmatter."""
    text = path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text
    return miniyaml.load(match.group(1)), text[match.end() :]


def write_doc(path: Path, meta: dict, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = "---\n" + miniyaml.dump(meta) + "\n---\n" + body
    path.write_text(text, encoding="utf-8", newline="\n")


def load_cards(notes_dir: Path, problems=None):
    """Load every card, and report the ones that could not be used.

    A card the user wrote must never disappear without a word -- silently
    skipping an unreadable card looks exactly like the note was never saved.
    """
    cards = []
    cards_dir = notes_dir / "cards"
    if not cards_dir.is_dir():
        return cards

    def complain(path, message):
        if problems is not None:
            problems.append((path, message))

    for path in sorted(cards_dir.glob("*.md")):
        meta, body = read_doc(path)
        if not isinstance(meta, dict) or not meta:
            complain(path, "檔案開頭讀不到 --- YAML 區塊，這張卡沒有被使用")
            continue
        meta.setdefault("id", path.stem.split("-")[0])

        anchor = meta.get("anchor")
        if anchor is None:
            complain(path, "沒有 anchor 欄位，不知道要掛在哪裡")
        elif not isinstance(anchor, dict):
            complain(path, "anchor 欄位格式不對（應該是縮排的 file / heading / quote）")
            meta["anchor"] = {}
        elif anchor.get("file") is not None and not isinstance(anchor.get("file"), str):
            complain(path, "anchor.file 不是檔案路徑，YAML 可能寫壞了")
            anchor["file"] = ""

        status = str(meta.get("status", "open"))
        if status not in VALID_STATUS:
            complain(path, f"status 是「{status}」，只能是 {' / '.join(VALID_STATUS)}")
        origin = str(meta.get("origin", "asked"))
        if origin not in VALID_ORIGIN:
            complain(path, f"origin 是「{origin}」，只能是 {' / '.join(VALID_ORIGIN)}")

        if not card_sections(body).get("問題", "").strip():
            complain(path, "沒有寫「## 問題」，複習時只會看到一張沒有問題的卡")

        cards.append({"path": path, "meta": meta, "body": body})

    seen = {}
    for card in cards:
        cid = str(card["meta"].get("id"))
        if cid in seen:
            complain(
                card["path"],
                f"編號 {cid} 和 {seen[cid].name} 重複，索引會出現兩個同號的疑問",
            )
        else:
            seen[cid] = card["path"]
    return cards


def card_sections(body: str):
    """Split a card body on '## ' headings into {heading: text}."""
    sections, current, buf = {}, None, []
    for line in body.splitlines():
        if line.startswith("## "):
            if current is not None:
                sections[current] = "\n".join(buf).strip()
            current, buf = line[3:].strip(), []
        else:
            buf.append(line)
    if current is not None:
        sections[current] = "\n".join(buf).strip()
    return sections


# --------------------------------------------------------------------------
# source discovery
# --------------------------------------------------------------------------


def is_meta_path(rel: Path) -> bool:
    if any(part.lower() in META_DIRNAMES for part in rel.parts[:-1]):
        return True
    return rel.name.lower() in META_FILENAMES


def discover_sources(paper_root: Path):
    """All markdown files that plausibly hold paper prose, in a stable order.

    Tier A packages get their order from INDEX.md; everything else is sorted by
    path. document.md is skipped when sections/ exists (same text twice).
    """
    all_md = []
    for path in sorted(paper_root.rglob("*.md")):
        rel = path.relative_to(paper_root)
        if is_meta_path(rel):
            continue
        all_md.append(rel)

    sections = [r for r in all_md if r.parts and r.parts[0] == "sections"]
    if sections:
        ordered = index_order(paper_root)
        known = [r for r in ordered if r in sections]
        rest = [r for r in sections if r not in known]
        return known + sorted(rest)
    return [r for r in all_md if r.name.lower() != "document.md"] or all_md


def index_order(paper_root: Path):
    """File order as listed in INDEX.md's chunk table, if it is parseable."""
    index = paper_root / "INDEX.md"
    if not index.is_file():
        return []
    order = []
    for match in re.finditer(r"`(sections/[^`]+\.md)`", index.read_text(encoding="utf-8")):
        rel = Path(match.group(1))
        if rel not in order:
            order.append(rel)
    return order


def looks_generated(paper_root: Path, sources) -> bool:
    """True when these "sources" are actually one of our own annotated trees."""
    for rel in list(sources)[:5]:
        try:
            head = (paper_root / rel).read_text(encoding="utf-8")[:2000]
        except OSError:
            continue
        if GENERATED_MARK in head:
            return True
    return False


def file_fingerprint(path: Path) -> str:
    return hashlib.sha1(path.read_bytes()).hexdigest()[:12]


# --------------------------------------------------------------------------
# anchor resolution
# --------------------------------------------------------------------------

_WS = re.compile(r"\s+")


def normalize(text: str) -> str:
    return _WS.sub(" ", text).strip()


def _norm_map(lines):
    """Normalized haystack plus a lookup from char offset back to line index."""
    pieces, spans, cursor = [], [], 0
    for idx, line in enumerate(lines):
        norm = normalize(line)
        if not norm:
            continue
        if pieces:
            cursor += 1
        spans.append((cursor, cursor + len(norm), idx))
        pieces.append(norm)
        cursor += len(norm)
    return " ".join(pieces), spans


def _block_end(lines, start: int) -> int:
    """Index of the last line of the blank-line-delimited block containing start."""
    i = start
    while i + 1 < len(lines) and lines[i + 1].strip():
        i += 1
    return i


def _display_math_end(lines, start: int) -> int:
    i = start
    while i + 1 < len(lines):
        i += 1
        if lines[i].strip() == "$$":
            return i
    return _block_end(lines, start)


def _find_ref(lines, ref: str):
    kind, _, value = ref.partition(":")
    kind, value = kind.strip().lower(), value.strip()
    if not value:
        return None

    if kind in ("eq", "equation"):
        pattern = re.compile(r"\\tag\{\s*" + re.escape(value) + r"\s*\}")
        for i, line in enumerate(lines):
            if pattern.search(line):
                return _display_math_end(lines, i), "ref:equation-tag"
        return None

    if kind in ("fig", "figure"):
        num = value.zfill(2)
        pattern = re.compile(r"!\[[^\]]*\]\([^)]*figure-0*" + re.escape(num.lstrip("0") or "0") + r"\b[^)]*\)")
        for i, line in enumerate(lines):
            if pattern.search(line) or re.search(r"figure-" + re.escape(num) + r"\.", line):
                after = i
                nxt = i + 1
                while nxt < len(lines) and not lines[nxt].strip():
                    nxt += 1
                if nxt < len(lines) and re.match(r"^Fig(ure)?\.?\s", lines[nxt].strip()):
                    after = _block_end(lines, nxt)
                return after, "ref:figure"
        return None

    if kind in ("table", "tbl"):
        num = value.zfill(2)
        for i, line in enumerate(lines):
            if re.search(r"table-" + re.escape(num) + r"[.\b]", line):
                return _block_end(lines, i), "ref:table"
        return None

    return None


def _find_heading(lines, heading_path):
    if not heading_path:
        return None
    if isinstance(heading_path, str):
        heading_path = [heading_path]
    target = normalize(str(heading_path[-1])).lower()
    exact, loose = [], []
    for i, line in enumerate(lines):
        if not line.startswith("#"):
            continue
        text = normalize(line.lstrip("#")).lower()
        if text == target:
            exact.append(i)
        elif len(target) > 6 and target in text:
            loose.append(i)
    if len(exact) == 1:
        return exact[0], "heading"
    if not exact and len(loose) == 1:
        return loose[0], "heading"
    # Several headings match: refuse to guess, same as an ambiguous quote.
    return None


def _find_quote(lines, quote):
    if not quote:
        return None
    exact = normalize(str(quote.get("exact") or "")) if isinstance(quote, dict) else normalize(str(quote))
    if len(exact) < 12:
        return None
    haystack, spans = _norm_map(lines)
    pos = haystack.find(exact)
    if pos < 0:
        return None
    if haystack.find(exact, pos + 1) >= 0:
        return None  # ambiguous: refuse to guess
    for start, end, idx in spans:
        if start <= pos < end:
            return _block_end(lines, idx), "quote"
    return None


def highlight_quote(lines, exact: str):
    """Wrap the anchored sentence in ==…== on the lines it covers.

    The card already knows which sentence tripped the reader up; marking it
    saves them re-reading the paragraph to find out where they were. Same
    refuse-to-guess rule as anchoring: unknown or ambiguous means no mark.

    ==…== rather than <mark>: the annotated Markdown stays portable (Obsidian
    and friends render it) and minimd turns it into <mark> for the page.
    """
    if not exact:
        return lines
    haystack, spans = _norm_map(lines)
    pos = haystack.find(exact)
    if pos < 0 or haystack.find(exact, pos + 1) >= 0:
        return lines
    end = pos + len(exact)

    out = list(lines)
    for start, stop, idx in spans:
        if stop <= pos or start >= end:
            continue
        fragment = haystack[max(start, pos) : min(stop, end)].strip()
        if len(fragment) < 4:
            continue
        # Match back into the raw line, tolerating the whitespace normalize() ate.
        pattern = r"\s+".join(re.escape(tok) for tok in fragment.split(" ") if tok)
        hits = list(re.finditer(pattern, out[idx]))
        if len(hits) != 1:
            continue
        head, body, tail = out[idx][: hits[0].start()], hits[0].group(0), out[idx][hits[0].end() :]
        # Never cut into math, code or a link target -- and never nest marks,
        # so a second card quoting the same line simply goes unmarked.
        if any(ch in body for ch in "$`") or "](" in body or "==" in out[idx]:
            continue
        out[idx] = f"{head}=={body}=={tail}"
    return out


def quote_text(quote) -> str:
    if isinstance(quote, dict):
        return normalize(str(quote.get("exact") or ""))
    return normalize(str(quote or ""))


def count_quote(lines, exact: str) -> int:
    """How many times a quote occurs in this file (whitespace-insensitive)."""
    if len(exact) < 12:
        return -1
    haystack, _ = _norm_map(lines)
    count, pos = 0, 0
    pos = haystack.find(exact)
    while pos >= 0:
        count += 1
        pos = haystack.find(exact, pos + 1)
    return count


def diagnose(anchor: dict, lines) -> str:
    """Why an anchor failed, phrased so the fix is obvious.

    "找不到" and "出現多次" need opposite fixes -- reporting both as
    "unresolved" makes the warning useless at the moment it matters.
    """
    if not anchor:
        return "這張卡沒有寫要掛在哪裡"
    problems = []
    if anchor.get("ref"):
        problems.append(f"這個檔案裡找不到 {anchor['ref']}（公式或圖表編號對不上）")
    if anchor.get("heading"):
        problems.append("這個檔案裡找不到指定的小節標題")

    exact = quote_text(anchor.get("quote"))
    count = count_quote(lines, exact)
    if count < 0:
        problems.append("沒有指定要掛在哪一句原文旁（quote.exact 需 12 字以上）")
    else:
        if count == 0:
            problems.append("這個檔案裡找不到你指定的那句原文（換一句，或執行 reanchor.py）")
        elif count > 1:
            problems.append(f"你指定的那句原文在這個檔案裡出現 {count} 次，無法確定是哪一處（把句子引長一點）")
    return "；".join(problems) or "無法解析"


def resolve_anchor(anchor: dict, lines):
    """Return (insert_after_line_index, method) or (None, reason).

    Ladder: ref -> heading -> quote. Each rung is verified against the real
    text; a rung that does not match falls through to the next one.
    """
    if not anchor:
        return None, "這張卡沒有寫要掛在哪裡"
    for finder in (
        lambda: _find_ref(lines, str(anchor.get("ref"))) if anchor.get("ref") else None,
        lambda: _find_heading(lines, anchor.get("heading")),
        lambda: _find_quote(lines, anchor.get("quote")),
    ):
        hit = finder()
        if hit:
            return hit[0], hit[1]
    return None, diagnose(anchor, lines)


# --------------------------------------------------------------------------
# link rewriting for the mirrored tree
# --------------------------------------------------------------------------

_LINK_RE = re.compile(r"(!?\[[^\]]*\]\()([^)\s]+)(\s*(?:\"[^\"]*\")?\))")
# Cards are emitted as raw HTML, so their back-links live in an attribute and
# the Markdown pattern never saw them -- they broke silently on every rebase.
_ATTR_RE = re.compile(r"(\b(?:href|src)=\")([^\"]+)(\")")


def rewrite_links(text: str, src_dir: Path, dst_dir: Path) -> str:
    """Re-relativize relative links so the mirrored file still resolves assets.

    Works on absolute directories, so the annotated tree may live anywhere --
    inside the paper package, beside it, or on the other side of the disk.
    """
    import posixpath

    def fix(match):
        target = match.group(2)
        if re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", target) or target.startswith(("/", "#")):
            return match.group(0)
        anchor = ""
        if "#" in target:
            target, _, anchor = target.partition("#")
            anchor = "#" + anchor
        if not target:
            return match.group(0)
        absolute = posixpath.normpath(posixpath.join(src_dir.as_posix(), target))
        rebased = posixpath.relpath(absolute, dst_dir.as_posix())
        return match.group(1) + rebased + anchor + match.group(3)

    return _ATTR_RE.sub(fix, _LINK_RE.sub(fix, text))




def rel_href(from_file: Path, to_file: Path) -> str:
    """A link from one generated file to another, both given as real paths."""
    import posixpath

    return posixpath.relpath(to_file.as_posix(), from_file.parent.as_posix())


SCHEMA = 2


def default_annotated(paper_root: Path, work_root: Path) -> Path:
    """Where the review page goes when nobody said.

    Beside the converted package rather than inside it: a paper folder normally
    holds the PDF plus a `<name>_md/` package of dozens of files, and a review
    page buried in there is a page nobody finds. One level up it sits next to
    the PDF, which is where the reader already looks.

    Only when the notes stayed with the paper. `--out` means the user placed the
    workspace deliberately, so the page stays with the notes they placed.
    """
    if work_root != paper_root:
        return work_root / "annotated"
    parent = paper_root.parent
    if parent == paper_root or parent == Path.home():
        return work_root / "annotated"
    package = paper_root.name.lower().endswith(("_md", "-md"))
    beside_pdf = any(parent.glob("*.pdf"))
    return parent / "annotated" if (package or beside_pdf) else work_root / "annotated"


def load_workspace(work_root: Path):
    """Locate the paper from the notes directory that points at it.

    Commands take the directory that holds notes/ -- which is the paper package
    itself unless probe.py was given --out. The review page is tracked
    separately: it may sit outside that directory entirely.
    """
    notes = work_root / "notes"
    config_path = notes / "paper.yml"
    if not config_path.is_file():
        raise SystemExit(f"找不到 {config_path}，請先執行 probe.py")
    config = miniyaml.load(config_path.read_text(encoding="utf-8"))
    if int(config.get("schema") or 1) < SCHEMA:
        raise SystemExit(
            f"{config_path} 是舊版格式，請重新執行一次 probe.py 以更新。"
        )
    paper_root = (work_root / str(config.get("paper_root") or ".")).resolve()
    # Older configs predate a movable review page; they meant work_root/annotated.
    annotated = (work_root / str(config.get("annotated_root") or "annotated")).resolve()
    return config, paper_root, notes, annotated
