"""Rebuild annotated/ and notes/QUESTIONS.md from the source text + cards.

Always a full rebuild from the untouched source, never an incremental edit of
a previous build -- that is what makes repeated runs idempotent. Nothing in
annotated/ is a source of truth; edit notes/cards/ instead.

Usage:
    python build_annotated.py <paper_root> [--allow-drift]
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

from . import anchors, cli, library, links, notes, sources, srs, workspace, xlinks

cli.bootstrap()

STATUS_LABEL = {"open": "未解決", "half": "半懂", "resolved": "已解決"}
STATUS_ICON = {"open": "🔴", "half": "🟡", "resolved": "🟢"}

GENERATED_BANNER = (
    "<!-- GENERATED by paper-annotations — 請勿手改。\n"
    "     權威原文：{source}\n"
    "     疑問卡來源：notes/cards/，要點來源：notes/points/\n"
    "     重新產生：python <scripts>/build_annotated.py <本次的路徑> -->\n"
)

ANNOTATED_AGENTS = """# Annotated View — Reading Policy

本目錄是**衍生檔**，由疑問卡與原文合併產生。

1. 權威原文在 `{paper}`，**引用論文內容一律以原文為準**。
2. 本目錄檔案中 `<details>` 區塊內的文字是**使用者的提問與 AI 的解說**，屬於閱讀筆記，
   **不是論文內容，不得作為論文原文引用或轉述為作者主張**。
3. `<div class="pnote">` 區塊是**AI 讀出的要點**（主張／方法／假設／定義／結果／限制），
   是對原文的轉述，**引用時一律回到權威原文查證**。
4. 不要編輯本目錄任何檔案；修改請改 `{cards}` 後重新執行 build。
5. 疑問索引在 `{questions}`。

本檔案為新增，不覆寫論文套件原有的 `AGENTS.md` 閱讀政策。
"""


def summary_text(card) -> str:
    """The whole question, on one line.

    Never shortened: the collapsed card is what the reader faces during review,
    and a half-shown question cannot be answered from memory. Long questions
    make a taller summary -- that is the right trade here.
    """
    sections = notes.card_sections(card["body"])
    question = sections.get("問題") or sections.get("Question") or ""
    return " ".join(question.split()) or "(未填問題)"


def render_card(card, dst_path: Path, out_links=(), in_links=()) -> str:
    meta, sections = card["meta"], notes.card_sections(card["body"])
    cid = str(meta.get("id", "?"))
    status = str(meta.get("status", "open"))
    icon = STATUS_ICON.get(status, "⚪")
    label = STATUS_LABEL.get(status, status)
    title = summary_text(card)

    origin = str(meta.get("origin", "asked"))
    tag_list = " ".join(str(t) for t in (meta.get("tags") or []))
    parts = [
        f"<!-- card:{cid} -->",
        # data-* attributes are inert in Markdown and let the HTML view filter;
        # the id gives the question list something to jump to.
        f'<details class="qcard" id="card-{cid}" data-id="{cid}" data-status="{status}" '
        f'data-origin="{origin}" data-tags="{tag_list}">',
        f"<summary>{icon} <b>Q{cid}</b> · {title} <sub>[{label}]</sub></summary>",
        "",
    ]

    # The question is not repeated in the body -- the summary already carries it
    # in full, whether the card is collapsed or open.
    #
    # Each part gets its own block so an opened card can be read at a glance:
    # where you were stuck, what the answer was, and the one line that brings it
    # back. Run together as bold-prefixed paragraphs they all looked alike.
    for key, kind in (("卡點", "stuck"), ("解答", "answer"), ("一句話直覺", "key")):
        value = (sections.get(key) or "").strip()
        if value:
            parts += [
                f'<div class="csec csec-{kind}"><b class="csec-t">{key}</b>',
                "",
                value,
                "",
                "</div>",
                "",
            ]

    parts += render_links(out_links, in_links)

    meta_bits = [f"狀態 {label}"]
    if meta.get("origin") == "suggested":
        meta_bits.append("AI 提示（非你提問）")
    if meta.get("created"):
        meta_bits.append(f"建立 {meta['created']}")
    tags = meta.get("tags") or []
    if tags:
        meta_bits.append("標籤 " + ", ".join(str(t) for t in tags))
    link = links.rel_href(dst_path, card["path"])
    meta_bits.append(f'<a href="{link}">卡片原始檔</a>')
    parts += ["<sub>" + " · ".join(meta_bits) + "</sub>", "", "</details>", ""]
    return "\n".join(parts)


def render_links(out_links, in_links) -> list:
    """Both ends of every link, on the note itself.

    Cross-paper targets are not hyperlinked: the other paper lives under its
    own root and the path that reaches it differs between disk and server, so a
    href would be right in one place and broken in the other. What the target
    actually says is shown instead, which is the part worth having anyway.
    """
    if not out_links and not in_links:
        return []
    rows = []
    for link in out_links:
        label = xlinks.LINK_TYPES[link["type"]][0]
        ref = link["ref"]
        rows.append(
            f'<div class="xl"><b class="xlt">{label}</b> '
            f'<code>{xlinks.ref_text(ref)}</code> {esc_html(link["summary"])}</div>'
        )
    for link in in_links:
        pair = xlinks.LINK_TYPES.get(link["type"])
        label = pair[1] if pair else link["type"]
        src = link["from"]
        rows.append(
            f'<div class="xl back"><b class="xlt">← {label}</b> '
            f'<code>{src["slug"]}#{src["kind"]}{src["id"]}</code> '
            f'{esc_html(link["summary"])}</div>'
        )
    return ['<div class="xlinks">'] + rows + ["</div>", ""]


def esc_html(text: str) -> str:
    return (
        str(text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    )


def render_point(point, dst_path: Path, out_links=(), in_links=()) -> str:
    """A point, rendered as quietly as it can be while still being findable.

    Not a <details>: there is nothing to hide behind a summary -- a point is
    one sentence, and hiding it would defeat the purpose of having written it
    down. Not a highlight either; the reader's own marks and the sentences he
    got stuck on already compete for the same page, and this must lose that
    competition.
    """
    meta = point["meta"]
    pid = str(meta.get("id", "?"))
    label = notes.KIND_LABEL.get(point["kind"], point["kind"])
    tags = [str(t) for t in (meta.get("tags") or [])]

    # The provenance caption that used to sit under every point is gone: one
    # line each, repeated down a page of points, cost more room than the paper
    # it was explaining. What it carried moves onto the kind badge, which was
    # already on that line and so costs nothing: the badge links to the source
    # file, and its tooltip still names the origin and the tags. Tags stay in
    # data-tags because the search box matches on text -- off the page they
    # would otherwise stop being searchable.
    bits = []
    if point["origin"] == "agent":
        bits.append("AI 讀出的要點，不是你寫的")
    if tags:
        bits.append("標籤 " + ", ".join(tags))
    bits.append("點一下開啟要點原始檔")
    title = esc_html(" · ".join(bits)).replace('"', "&quot;")

    return "\n".join(
        [
            f"<!-- point:{pid} -->",
            f'<div class="pnote" id="point-{pid}" data-id="{pid}" '
            f'data-kind="{point["kind"]}" data-origin="{point["origin"]}" '
            f'data-tags="{" ".join(tags)}">'
            f'<a class="pk" href="{links.rel_href(dst_path, point["path"])}" '
            f'title="{title}">{label}</a>',
            "",
            point["text"],
            "",
        ]
        + render_links(out_links, in_links)
        + [
            "</div>",
            "",
        ]
    )


def check_drift(paper_root: Path, config: dict):
    recorded = config.get("fingerprint", {}).get("files") or {}
    stale, missing = [], []
    for rel, digest in recorded.items():
        path = paper_root / rel
        if not path.is_file():
            missing.append(rel)
        elif sources.file_fingerprint(path) != digest:
            stale.append(rel)
    # A file added since the probe would otherwise be skipped in silence:
    # never annotated, never mentioned.
    current = {rel.as_posix() for rel in sources.discover_sources(paper_root)}
    added = sorted(current - set(recorded))
    return stale, missing, added


def build(work_root: Path, allow_drift: bool = False):
    config, paper_root, notes_dir, annotated_root = workspace.load_workspace(work_root)

    stale, missing, added = check_drift(paper_root, config)
    if (stale or missing or added) and not allow_drift:
        print("⚠️  論文原文和上次檢查時不一樣了，已停止建置：")
        for rel in missing:
            print(f"    檔案不見了   {rel}")
        for rel in stale:
            print(f"    內容有變動   {rel}")
        for rel in added:
            print(f"    多了新檔案   {rel}")
        if stale or missing:
            print("\n原文可能被重新轉檔或重新切分，你的筆記有掛錯位置的風險。請先執行：")
            print("    python <scripts>/reanchor.py <本次的路徑>")
            print("確認每則筆記都還掛在該在的地方，再重新建置。")
        else:
            print("\n新檔案不會被納入筆記，除非重新探測一次：")
            print("    python <scripts>/probe.py <論文路徑> [--out <筆記路徑>]")
        print("若確定這次變動跟筆記位置無關，可加 --allow-drift 略過這項檢查。")
        return 2

    card_problems = []
    cards = notes.load_cards(notes_dir, card_problems)
    points = notes.load_points(notes_dir, card_problems)
    by_file, points_by_file = {}, {}
    for card in cards:
        anchor = card["meta"].get("anchor") or {}
        by_file.setdefault(str(anchor.get("file") or ""), []).append(card)
    for point in points:
        anchor = point["meta"].get("anchor") or {}
        points_by_file.setdefault(str(anchor.get("file") or ""), []).append(point)

    source_list = [Path(p) for p in (config.get("sources") or [])]
    placed, unanchored, rows, fragile = {}, [], [], []
    point_rows, point_lost, point_fragile = [], [], []

    # Links resolve against the catalogs that exist right now, so a paper added
    # later lights up the links pointing at it on the next build of either side
    # -- nothing has to be rewritten.
    this_slug = library.paper_name(paper_root).lower()
    registry = library.find_registry(work_root)
    catalogs = xlinks.index(registry) if registry else {}
    back = xlinks.incoming(catalogs, this_slug)
    link_problems, broken_links = [], []

    def links_for(note, kind: str):
        meta = note["meta"]
        key = f"{kind}{str(meta.get('id') or '').zfill(4)}"
        declared = xlinks.declared(meta, this_slug, link_problems, note["path"].name)
        good, missing = xlinks.resolve(declared, catalogs, this_slug)
        for item in missing:
            broken_links.append((note["path"].name, xlinks.ref_text(item["ref"]), item["why"]))
        return good, back.get(key, [])

    for order, rel in enumerate(source_list):
        src = paper_root / rel
        if not src.is_file():
            continue
        lines = links.normalize_ref_links(src.read_text(encoding="utf-8").splitlines())
        dst = annotated_root / rel

        insertions = []
        for card in by_file.get(rel.as_posix(), []):
            index, method = anchors.resolve_anchor(card["meta"].get("anchor") or {}, lines)
            if index is None:
                unanchored.append((card, method))
                continue
            insertions.append((index, method, card))
            placed[str(card["meta"].get("id"))] = True
            # Check the quote even when the card anchored via ref/heading: a bad
            # quote stays invisible until the day the paper is re-converted,
            # which is exactly the day it is needed.
            anchor = card["meta"].get("anchor") or {}
            hits = anchors.count_quote(lines, anchors.quote_text(anchor.get("quote")))
            if hits != 1:
                fragile.append((card, hits))

        # Points resolve against the same untouched lines, by the same ladder.
        # They are never highlighted: the reader's own marks and the sentences
        # he got stuck on already compete for this page, and a point that shouts
        # as loudly as a question would drown out the question.
        point_hits = []
        for point in points_by_file.get(rel.as_posix(), []):
            anchor = point["meta"].get("anchor") or {}
            # Quote only, not the ref -> heading -> quote ladder cards climb. A
            # card is about a place in the argument, so landing at the top of
            # its section is fine; a point restates one specific sentence, and
            # sitting a page above that sentence would make it say the wrong
            # thing about the wrong text. heading stays in the file as a label.
            index, method = anchors.resolve_anchor({"quote": anchor.get("quote")}, lines)
            if index is None:
                point_lost.append((point, method))
                continue
            point_hits.append((index, point))
            hits = anchors.count_quote(lines, anchors.quote_text(anchor.get("quote")))
            if hits != 1:
                point_fragile.append((point, hits))
            point_rows.append(
                {"order": (order, index), "point": point, "file_rel": rel, "dst": dst}
            )

        # Rebase the paper's own links before the cards go in: a card's link was
        # already computed against dst, so a rewrite of the merged text would
        # move it a second time. Anchoring still runs on the untouched lines.
        out = [links.rewrite_links(line, src.parent, dst.parent) for line in lines]
        # Marking runs before insertion: it never changes the line count, so the
        # anchor indices resolved above still point where they did.
        for _, _, card in insertions:
            quote = (card["meta"].get("anchor") or {}).get("quote")
            out = anchors.highlight_quote(out, anchors.quote_text(quote))
        blocks = [
            (index, render_card(card, dst, *links_for(card, "Q")).splitlines())
            for index, _, card in insertions
        ]
        blocks += [
            (index, render_point(point, dst, *links_for(point, "P")).splitlines())
            for index, point in point_hits
        ]
        for index, block in sorted(blocks, key=lambda item: -item[0]):
            out[index + 1 : index + 1] = [""] + block

        for index, method, card in insertions:
            rows.append(
                {
                    "order": (order, index),
                    "card": card,
                    "method": method,
                    "file_rel": rel,
                    "dst": dst,
                }
            )

        text = "\n".join(out).rstrip("\n") + "\n"
        banner = GENERATED_BANNER.format(source=rel.as_posix())
        # keep the banner below any YAML frontmatter, or it stops being frontmatter
        match = notes.FRONTMATTER_RE.match(text)
        if match:
            text = text[: match.end()] + "\n" + banner + text[match.end() :]
        else:
            text = banner + "\n" + text
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(text, encoding="utf-8", newline="\n")

    # Drop files from a previous build that no longer correspond to a source --
    # but only inside a directory we can prove is ours. The review page can now
    # be pointed anywhere, and pruning someone's own folder is unrecoverable.
    annotated_root.mkdir(parents=True, exist_ok=True)
    marker = annotated_root / "AGENTS.md"
    keep = {(annotated_root / rel).resolve() for rel in source_list}
    keep.add(marker.resolve())
    for path in annotated_root.rglob("*.md"):
        if path.resolve() in keep:
            continue
        # Delete only what a previous build wrote. The review page can be
        # pointed at any directory, and a file we did not create is not ours
        # to remove -- however stale it looks from in here.
        try:
            head = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if sources.GENERATED_MARK in head:
            path.unlink()

    marker.write_text(
        "<!-- paper-annotations -->\n"
        + ANNOTATED_AGENTS.format(
            paper=links.rel_href(marker, paper_root),
            cards=links.rel_href(marker, notes_dir / "cards"),
            questions=links.rel_href(marker, notes_dir / "QUESTIONS.md"),
        ),
        encoding="utf-8",
        newline="\n",
    )

    for card in cards:
        cid = str(card["meta"].get("id"))
        if cid not in placed and not any(c["meta"].get("id") == card["meta"].get("id") for c, _ in unanchored):
            declared = (card["meta"].get("anchor") or {}).get("file") or "(未填)"
            unanchored.append((card, f"找不到這張卡指定的檔案：{declared}（原文可能被重新切分，執行 reanchor.py）"))

    write_index(paper_root, notes_dir, annotated_root, config, rows, unanchored, cards,
                fragile, card_problems, point_rows, point_lost)
    review = srs.counts(notes_dir, cards, date.today().isoformat())
    catalog = library.write_catalog(notes_dir, paper_root, config, cards, points, review)

    print(f"註記檢視    {len(source_list)} 個檔案 → {annotated_root}")
    print(f"疑問卡      {len(cards)} 張：已定位 {len(rows)}，找不到位置 {len(unanchored)}")
    for card, reason in unanchored:
        print(f"  ⚠️  Q{card['meta'].get('id')} — {reason} — {card['path'].name}")
    if points or point_lost:
        print(f"要點        {len(points)} 則：已定位 {len(point_rows)}，找不到位置 {len(point_lost)}")
        for point, reason in point_lost:
            print(f"  ⚠️  要點 {point['meta'].get('id')} — {reason} — {point['path'].name}")
    print(f"跨論文目錄  {catalog}")
    if card_problems:
        # cards and points share the list, so the wording has to cover both
        print("\n⚠️  這些筆記本身有問題：")
        for path, message in card_problems:
            print(f"    {path.name} — {message}")
    if fragile:
        print("\n🟡 引文提醒（這次照樣掛好了，但論文改版後會救不回來）：")
        for card, hits in fragile:
            print(f"    Q{card['meta'].get('id')} — {fragile_reason(hits)} — {card['path'].name}")
        print("    把 quote.exact 改成原文中獨一無二的一句話即可。")
    if point_fragile:
        print("\n🟡 要點的引文提醒（這次照樣掛好了，但論文改版後會救不回來）：")
        for point, hits in point_fragile:
            print(f"    要點 {point['meta'].get('id')} — {fragile_reason(hits)} — {point['path'].name}")

    linked = sum(len(v) for v in back.values())
    if catalogs and (linked or broken_links or link_problems):
        print(f"\n跨論文連結  指進來的 {linked} 條")
    for name, message in link_problems:
        print(f"  ⚠️  {name} — {message}")
    for name, target, why in broken_links:
        print(f"  ⚠️  {name} 指向 {target} — {why}")
    if broken_links:
        print("      連結解不到就是解不到，不會猜。修掉目標或先 build 那一篇。")

    companions = drifted_companions(paper_root, config)
    if companions:
        print("\n🟡 這些檔案也變了（不影響筆記位置，僅供參考）：")
        for rel in companions:
            print(f"    {rel}")
    return 0


def fragile_reason(hits: int) -> str:
    if hits < 0:
        return "沒寫引文，或引文太短"
    if hits == 0:
        return "引文在這個檔案裡找不到"
    return f"引文在這個檔案裡出現 {hits} 次，不唯一"


def drifted_companions(paper_root: Path, config: dict):
    """document.md / INDEX.md / manifest.json changed but the sections did not.

    These cannot break an anchor -- notes hang on sections/ -- so this never
    stops a build. It is still worth saying: it usually means the package is
    internally inconsistent, or a re-conversion only half landed.
    """
    out = []
    for rel, digest in (config.get("fingerprint", {}).get("companions") or {}).items():
        path = paper_root / rel
        if not path.is_file():
            out.append(f"{rel}（檔案不見了）")
        elif sources.file_fingerprint(path) != digest:
            out.append(f"{rel}（內容有變動）")
    return out


def esc(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def anchor_display(card, method) -> str:
    anchor = card["meta"].get("anchor") or {}
    if anchor.get("ref"):
        kind, _, value = str(anchor["ref"]).partition(":")
        pretty = {"eq": "Eq.", "equation": "Eq.", "fig": "Fig.", "figure": "Fig.", "table": "Table "}
        if method.startswith("ref:"):
            return f"{pretty.get(kind.lower(), kind + ':')}{value}"
    return {"heading": "小節", "quote": "引文"}.get(method, method)


def write_index(paper_root: Path, notes_dir: Path, annotated_root: Path, config: dict, rows, unanchored, cards, fragile=(), card_problems=(), point_rows=(), point_lost=()):
    rows = sorted(rows, key=lambda r: r["order"])
    page = annotated_root / "index.html"
    annotated_link = links.rel_href(notes_dir / "QUESTIONS.md", page)
    lines = [
        "<!-- GENERATED by paper-annotations — 請勿手改，改 notes/cards/ 後重新 build。 -->",
        "",
        "# 疑問索引",
        "",
        f"論文套件：`{paper_root.name}` · Tier {config.get('tier', '?')} · "
        f"建置 {date.today().isoformat()} · built_by: python",
        "",
        f"共 {len(cards)} 張疑問卡（已定位 {len(rows)}，找不到位置 {len(unanchored)}）。",
        f"複習入口是 [`{annotated_link}`]({annotated_link})：原文中就地摺疊著你當初的問題，先自己想過再展開。",
        "",
    ]

    if card_problems:
        lines += [
            "## ⚠️ 筆記本身有問題",
            "",
            "這些檔案沒辦法正常使用。**沒有 YAML 區塊的檔案完全不會被讀取**，"
            "內容還在檔案裡，但不會出現在任何地方。",
            "",
            "| 檔案 | 問題 |",
            "|---|---|",
        ]
        for path, message in card_problems:
            # the link has to point at the folder the file actually came from
            folder = path.parent.name
            lines.append(f"| [`{path.name}`]({folder}/{path.name}) | {esc(message)} |")
        lines.append("")

    if unanchored:
        lines += [
            "## ⚠️ 找不到位置的疑問",
            "",
            "這些疑問在原文中找不到對應位置，**不會出現在註記檢視裡**。請改卡片裡指定的那句原文，或執行 `reanchor.py`。",
            "",
            "| 卡片 | 原因 | 問題 |",
            "|---|---|---|",
        ]
        for card, reason in unanchored:
            lines.append(
                f"| [`{card['path'].name}`](cards/{card['path'].name}) | {esc(reason)} | {esc(summary_text(card))} |"
            )
        lines.append("")

    if fragile:
        lines += [
            "## 🟡 引文需要修補",
            "",
            "這些疑問目前掛得上，但它們指定的原文句子不唯一或找不到。"
            "論文一旦重新轉檔，就沒辦法自動找回位置——趁現在把 `quote.exact` 改成原文中獨一無二的一句。",
            "",
            "| 卡片 | 問題 | 狀況 |",
            "|---|---|---|",
        ]
        for card, hits in fragile:
            lines.append(
                f"| [`{card['path'].name}`](cards/{card['path'].name}) "
                f"| {esc(summary_text(card))} | {esc(fragile_reason(hits))} |"
            )
        lines.append("")

    pending = [r for r in rows if str(r["card"]["meta"].get("status", "open")) in ("open", "half")]
    if pending:
        lines += ["## 🔶 還沒完全懂", "", "| 狀態 | 問題 | 位置 |", "|---|---|---|"]
        for row in pending:
            card = row["card"]
            status = str(card["meta"].get("status", "open"))
            heading = (card["meta"].get("anchor") or {}).get("heading") or []
            where = esc(heading[-1]) if isinstance(heading, list) and heading else row["file_rel"].stem
            link = links.rel_href(notes_dir / "QUESTIONS.md", row["dst"])
            lines.append(
                f"| {STATUS_ICON.get(status, '⚪')} {STATUS_LABEL.get(status, status)} "
                f"| {esc(summary_text(card))} | [{where}]({link}) |"
            )
        lines.append("")

    lines += [
        "## 全部疑問（依論文順序）",
        "",
        "| # | 狀態 | 問題 | 小節 | 掛在哪 | 標籤 | 日期 | 卡片 |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        card = row["card"]
        meta = card["meta"]
        status = str(meta.get("status", "open"))
        anchor = meta.get("anchor") or {}
        heading = anchor.get("heading") or []
        where = esc(heading[-1]) if isinstance(heading, list) and heading else row["file_rel"].stem
        link = links.rel_href(notes_dir / "QUESTIONS.md", row["dst"])
        tags = ", ".join(str(t) for t in (meta.get("tags") or []))
        origin = " 💡" if meta.get("origin") == "suggested" else ""
        lines.append(
            f"| Q{meta.get('id')}{origin} | {STATUS_ICON.get(status, '⚪')} {STATUS_LABEL.get(status, status)} "
            f"| [{esc(summary_text(card))}]({link}) | {where} | {esc(anchor_display(card, row['method']))} "
            f"| {esc(tags)} | {esc(meta.get('created', ''))} | [卡片](cards/{card['path'].name}) |"
        )
    lines += ["", "💡 = 我主動標記的疑點，不是你問過的。", ""]

    # Below the questions and counted separately: points are the paper's
    # skeleton, not things the reader is waiting to understand. Folding them
    # into "疑問 N 則" would make that number stop meaning anything.
    if point_rows or point_lost:
        point_rows = sorted(point_rows, key=lambda r: r["order"])
        lines += [
            "## 要點（不是疑問）",
            "",
            f"共 {len(point_rows) + len(point_lost)} 則，AI 讀出的論文骨架，"
            "用來和其他論文對照。**不列入上面的疑問統計。**",
            "",
            "| 類型 | 一句話 | 小節 | 標籤 | 要點檔 |",
            "|---|---|---|---|---|",
        ]
        for row in point_rows:
            point = row["point"]
            meta = point["meta"]
            anchor = meta.get("anchor") or {}
            heading = anchor.get("heading") or []
            where = esc(heading[-1]) if isinstance(heading, list) and heading else row["file_rel"].stem
            link = links.rel_href(notes_dir / "QUESTIONS.md", row["dst"])
            tags = ", ".join(str(t) for t in (meta.get("tags") or []))
            lines.append(
                f"| {notes.KIND_LABEL.get(point['kind'], point['kind'])} "
                f"| [{esc(point['text'])}]({link}) | {where} | {esc(tags)} "
                f"| [要點](points/{point['path'].name}) |"
            )
        for point, reason in point_lost:
            lines.append(
                f"| {notes.KIND_LABEL.get(point['kind'], point['kind'])} "
                f"| {esc(point['text'])} | ⚠️ {esc(reason)} |  "
                f"| [要點](points/{point['path'].name}) |"
            )
        lines.append("")

    (notes_dir / "QUESTIONS.md").write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main(argv):
    args = cli.positionals(argv)
    return build(Path(args[0] if args else ".").resolve(), "--allow-drift" in argv)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
