"""Render the annotated Markdown into one self-contained review page.

Reads what build_annotated.py already produced -- so question placement is
decided in exactly one place and the two views can never disagree.

The page's stylesheet and script live in assets/ as real .css/.js files and
are inlined verbatim at build time -- the output is still a single file, but
the sources are editable with normal tooling.

Usage:
    python build_html.py <work> [--embed-assets] [--to <檔案>]

--embed-assets inlines every image as a data: URI, producing one large file
that can be sent to someone else as-is. Without it, images are referenced by
relative path (much smaller and faster to open).

--to writes somewhere other than annotated/index.html, which is what makes a
shareable copy possible without disturbing the page being read.
"""

from __future__ import annotations

import html
import json
import re
import sys
from datetime import date
from pathlib import Path

from . import cli, katex, links, minimd, notes, page_transforms as transforms, workspace

cli.bootstrap()

ASSETS = Path(__file__).resolve().parent / "assets"

# Runs before the body paints, so a reader who picked dark never sees a white
# flash on load. file:// may refuse localStorage, hence the try/catch.
THEME_BOOT = """<script>
(function(){try{var t=localStorage.getItem("pa-theme");
if(t==="light"||t==="dark")document.documentElement.setAttribute("data-theme",t);}catch(e){}})();
</script>"""


def build(work_root: Path, embed: bool = False, to: str = "") -> int:
    config, paper_root, notes_dir, annotated = workspace.load_workspace(work_root)
    if not annotated.is_dir():
        raise SystemExit(f"找不到註記檢視 {annotated}，請先執行 build_annotated.py")
    # --to keeps a shareable copy out of the way of the page being read.
    # Embedding into index.html would swap the working page for a much larger
    # one, and the next ordinary build would quietly swap it back again.
    out = Path(to).resolve() if to else annotated / "index.html"
    out.parent.mkdir(parents=True, exist_ok=True)

    style = (ASSETS / "style.css").read_text(encoding="utf-8")
    script = (ASSETS / "page.js").read_text(encoding="utf-8")

    source_list = [Path(p) for p in (config.get("sources") or [])]
    body_parts, toc, used = [], [], {}
    missing = []

    for rel in source_list:
        src = annotated / rel
        if not src.is_file():
            missing.append(rel.as_posix())
            continue
        text = src.read_text(encoding="utf-8")
        text = notes.FRONTMATTER_RE.sub("", text, count=1)
        text = re.sub(r"<!--\s*GENERATED by paper-annotations.*?-->", "", text, flags=re.DOTALL)
        # links inside annotated/sections/X.md are relative to that folder;
        # the page lives at annotated/index.html
        text = links.rewrite_links(text, src.parent, out.parent)

        def hook(level, title, _used=used):
            anchor = transforms.slugify(title, _used)
            toc.append((level, title, anchor))
            return anchor

        rendered, _ = minimd.render(text, heading_hook=hook)
        # data-src so a highlight drawn in the browser can name the file it
        # belongs to, in the form a mark file has to write down
        body_parts.append(
            f'<section class="chunk" id="{rel.stem}" data-src="{rel.as_posix()}">'
            f"{rendered}</section>"
        )

    cards = notes.load_cards(notes_dir)
    points = notes.load_points(notes_dir)
    # No points, no button: a paper that never had any renders exactly the page
    # it rendered before this feature existed.
    point_toggle = (
        '\n    <button id="showpt" class="on">論文要點</button>' if points else ""
    )
    marks, placed, mark_bad, mark_soft = transforms.collect_marks(notes_dir, paper_root)
    # "</" would end the script element early whatever it sits inside
    mark_json = json.dumps(placed, ensure_ascii=False).replace("</", "<\\/")
    body_parts = [transforms.tag_marks(part, cards) for part in body_parts]
    # One pass over the whole page: a section often points at a figure that
    # lives in another section, so the target table must be complete first.
    whole, algos = transforms.wrap_algorithms("".join(body_parts))
    whole, targets = transforms.label_ids(whole)
    targets.update(algos)
    whole, xrefs, xref_missing = transforms.linkify_xrefs(whole, targets)
    body_parts = [whole]
    counts = {"open": 0, "half": 0, "resolved": 0}
    for card in cards:
        counts[str(card["meta"].get("status", "open"))] = (
            counts.get(str(card["meta"].get("status", "open")), 0) + 1
        )

    nav = "".join(
        f'<a class="lv{min(level, 3)}" href="#{anchor}">{html.escape(title)}</a>'
        for level, title, anchor in toc
    )

    questions = transforms.collect_questions("".join(body_parts))
    qlist = "".join(
        f'<a class="qlink" href="#card-{q["id"]}" data-status="{q["status"]}" '
        f'data-origin="{q["origin"]}">'
        f'<span class="dot {q["status"]}">●</span>'
        f'<span class="qtext">{html.escape(q["text"])}</span></a>'
        for q in questions
    ) or '<div class="qempty">還沒有任何疑問</div>'

    title = paper_root.name
    manifest = paper_root / "manifest.json"
    if manifest.is_file():
        try:
            title = json.loads(manifest.read_text(encoding="utf-8")).get("title") or title
        except (ValueError, OSError):
            pass

    warn = ""
    if missing:
        warn = (
            '<div class="banner warn">下列章節在 annotated/ 裡找不到，'
            "請重新執行 build_annotated.py：" + html.escape("、".join(missing)) + "</div>"
        )

    page = f"""<!doctype html>
<html lang="zh-Hant">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)} — 疑問註記</title>
{THEME_BOOT}
<style>{style}</style>
{katex.katex_assets()}
</head>
<body data-paper="{html.escape(paper_root.name)}">
<div id="layout">
<div id="sidewrap">
<button id="sidetoggle" title="目錄與疑問">☰<span class="stxt">&nbsp;目錄與疑問</span></button>
<nav id="side">
  <div class="controls">
    <select id="statusf">
      <option value="all">全部狀態</option>
      <option value="open">未解決</option>
      <option value="half">半懂</option>
      <option value="resolved">已解決</option>
      <option value="none">不顯示疑問</option>
    </select>
    <button id="showai" class="on">AI 提示卡</button>{point_toggle}
  </div>
  <div class="controls"><input id="q" type="search" placeholder="搜尋疑問內容…"></div>
  <h2>螢光筆</h2>
  <div class="controls">
    <button id="hlon" class="on">🖍 顯示畫記</button>
    <button id="hlsave" hidden>💾 存檔</button>
    <button id="hlcopy">複製畫記</button>
    <button id="hlclear">清空</button>
  </div>
  <div id="hlstat"></div>
  <h2>疑問（{len(questions)}）</h2>
  <div id="qlist">{qlist}</div>
  <h2>目錄</h2>
  {nav}
</nav>
</div>
<main id="main">
<div class="meta">疑問 {len(cards)} 則 —
🔴 未解決 {counts.get('open', 0)} ·
🟡 半懂 {counts.get('half', 0)} ·
🟢 已解決 {counts.get('resolved', 0)} ·
產生於 {date.today().isoformat()}</div>
{warn}
<div class="banner">
本頁是<strong>衍生檔</strong>，由論文原文與 <code>notes/cards/</code> 合併產生，請勿直接編輯。
摺疊區塊裡的內容是<strong>你的提問與 AI 的解說，不是論文內容</strong>。
正文裡<strong>反白的句子</strong>就是你當初卡住的地方，點它會叫出當時的問題；
先自己想過再看解答。滑鼠移到左上角的 <strong>☰</strong> 會滑出目錄與疑問清單，點一下可以釘住；
右上角有提問草稿區。
選取正文會浮出<strong>螢光筆</strong>，畫記存在這台瀏覽器裡，要留下來請用側欄的「複製畫記」貼回對話。
</div>
{''.join(body_parts)}
</main>
</div>
<button id="theme">🌗 跟隨系統</button>
<div id="notewrap">
<button id="notetab">✎ 提問草稿</button>
<section id="note">
  <div class="nhead">提問草稿 <span class="nhint">讀完整段再一次問，複製後貼回對話</span></div>
  <textarea id="notepad" placeholder="例：IV-B 的 dc removal 為什麼要扣掉平均密度？&#10;（這裡只是草稿，不會送出，也不會變成卡片）"></textarea>
  <div class="nbar"><button id="ncopy">複製</button><button id="nclear">清空</button>
  <button id="noteclose">✕ 收起</button><span id="nstat"></span></div>
</section>
</div>
<script id="pa-marks" type="application/json">{mark_json}</script>
<div id="hltip" hidden></div>
<section id="hlnote" hidden>
  <div class="nhead">畫記註解 <span class="nhint">存在瀏覽器，複製後交給 agent 落檔</span></div>
  <textarea id="hlnotepad" placeholder="這段為什麼重要？想到什麼？"></textarea>
  <div class="nbar"><button id="hlnoteok">儲存</button><button id="hlnotedel">刪除畫記</button>
  <button id="hlnotecancel">取消</button></div>
</section>
<div id="hlbar" hidden>
<button data-c="1" title="黃色畫記" aria-label="黃色畫記"></button>
<button data-c="2" title="綠色畫記" aria-label="綠色畫記"></button>
<button data-c="3" title="藍色畫記" aria-label="藍色畫記"></button>
<button data-c="4" title="紅色畫記" aria-label="紅色畫記"></button>
<button id="hlnotebtn" title="寫註解" aria-label="寫註解">✎</button>
<button id="hldel" title="清除這條畫記" aria-label="清除這條畫記" hidden>✕</button>
</div>
<div id="ov" hidden></div>
<aside id="panel" hidden tabindex="-1" role="dialog" aria-modal="true"><div class="pbar">
<button id="pjump" data-tip="跳到原文" aria-label="跳到原文">⤴</button>
<button id="pclose" data-tip="關閉" aria-label="關閉">✕</button></div>
<div id="panel-in"></div></aside>
<script>{script}</script>
</body>
</html>
"""

    inlined, lost = 0, []
    if embed:
        # resolved against the file being written, not against annotated/:
        # every src was rewritten relative to wherever this page is landing
        page, inlined, lost = transforms.embed_images(page, out.parent)

    out.write_text(page, encoding="utf-8", newline="\n")
    size = out.stat().st_size / 1024
    print(f"{out.name}  {len(source_list)} 個章節、{len(cards)} 則疑問、{size:,.0f} KB")
    print(f"            演算法區塊 {len(algos)} 個、圖表交叉引用 {xrefs} 處已可點擊")
    if points:
        print(f"            要點 {len(points)} 則（側欄可一鍵隱藏）")
    if marks:
        noted = sum(1 for mark in marks if mark["note"])
        print(f"            畫記 {len(marks)} 條：已定位 {len(placed)}、有註解 {noted}")
    for name, why in mark_bad:
        print(f"  🔴 畫記 {name}：{why}")
    for name, why in mark_soft:
        print(f"  🟡 畫記 {name}：{why}")
    if xref_missing:
        listed = "、".join(f"{k}×{v}" for k, v in sorted(xref_missing.items())[:6])
        print(f"  🟡 這些引用找不到對應的圖或表，維持純文字：{listed}")
    print(f"  {out}")
    if embed:
        print(f"  已內嵌 {inlined} 張圖片：這個檔案可以單獨寄給別人。")
        if lost:
            listed = "、".join(lost[:4])
            print(f"  🔴 有 {len(lost)} 張圖片找不到檔案，收件人會看到破圖：{listed}")
    else:
        print("  圖片使用相對路徑；要單檔攜帶請加 --embed-assets。")
    if missing:
        print("  ⚠️  有章節缺漏，請先重新執行 build_annotated.py")
    return 0


def main(argv):
    args = cli.positionals(argv, value_flags={"--to"})
    return build(
        Path(args[0] if args else ".").resolve(),
        embed="--embed-assets" in argv,
        to=cli.flag(argv, "to", "") or "",
    )


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
