"""Source discovery: which markdown files hold the paper, in what order."""

from __future__ import annotations

import hashlib
import re
from pathlib import Path

GENERATED_MARK = "GENERATED by paper-annotations"

# Files that are never paper content, whatever tier we are in.
META_FILENAMES = {
    "readme.md",
    "index.md",
    "agents.md",
    "claude.md",
    "questions.md",
    "contributing.md",
    "changelog.md",
    "license.md",
}
META_DIRNAMES = {"notes", "annotated", "validation", "docs", ".git", "tools"}


def is_meta_path(rel: Path) -> bool:
    if any(part.lower() in META_DIRNAMES for part in rel.parts[:-1]):
        return True
    return rel.name.lower() in META_FILENAMES


def discover_sources(paper_root: Path):
    """All markdown files that plausibly hold paper prose, in a stable order.

    Tier A packages get their order from INDEX.md; everything else is sorted by
    path. document.md is skipped when sections/ exists (same text twice).
    """
    all_md = []
    for path in sorted(paper_root.rglob("*.md")):
        rel = path.relative_to(paper_root)
        if is_meta_path(rel):
            continue
        all_md.append(rel)

    sections = [r for r in all_md if r.parts and r.parts[0] == "sections"]
    if sections:
        ordered = index_order(paper_root)
        known = [r for r in ordered if r in sections]
        rest = [r for r in sections if r not in known]
        return known + sorted(rest)
    return [r for r in all_md if r.name.lower() != "document.md"] or all_md


def index_order(paper_root: Path):
    """File order as listed in INDEX.md's chunk table, if it is parseable."""
    index = paper_root / "INDEX.md"
    if not index.is_file():
        return []
    order = []
    for match in re.finditer(r"`(sections/[^`]+\.md)`", index.read_text(encoding="utf-8")):
        rel = Path(match.group(1))
        if rel not in order:
            order.append(rel)
    return order


def looks_generated(paper_root: Path, sources) -> bool:
    """True when these "sources" are actually one of our own annotated trees."""
    for rel in list(sources)[:5]:
        try:
            head = (paper_root / rel).read_text(encoding="utf-8")[:2000]
        except OSError:
            continue
        if GENERATED_MARK in head:
            return True
    return False


def file_fingerprint(path: Path) -> str:
    return hashlib.sha1(path.read_bytes()).hexdigest()[:12]
